const R = require('ramda');

function generateName() {
  const firstNames = [
    'Minh',
    'Zachariah',
    'Julio',
    'Val',
    'Darrin',
    'Marcelino',
    'Christian',
    'Nathanael',
    'Garfield',
    'Lionel',
    'Alonso',
    'Vernon',
    'Monroe',
    'Norberto',
    'Bruno',
    'Hershel',
    'Elvis',
    'Hank',
    'Bill',
    'Claudio',
    'Josh',
    'Clarence',
    'Emil',
    'Calvin',
    'Allan',
    'Jacinto',
    'Harrison',
    'Gabriel',
    'Gerry',
    'Reid',
    'Riley',
    'Mauro',
    'Sebastian',
    'Billy',
    'Bob',
    'Donn',
    'Terence',
    'Otha',
    'Henry',
    'Everette',
    'Elliot',
    'Barney',
    'Trenton',
    'Rolando',
    'Lacy',
    'Samuel',
    'Mohammed',
    'Rupert',
    'Davis',
    'Rey',
    'Lane',
    'Bradford',
    'Jarred',
    'Harley',
    'Carlton',
    'Lawerence',
    'Corey',
    'Rick',
    'Elvin',
    'Moses',
    'Larry',
    'Claud',
    'Palmer',
    'Rolf',
    'Willard',
    'Ezra',
    'Roscoe',
    'Fritz',
    'Ellsworth',
    'Luigi',
    'Buddy',
    'Abraham',
    'Rickie',
    'Roosevelt',
    'Dominic',
    'Winston',
    'Frederic',
    'Francesco',
    'Bobby',
    'Everett',
    'Hollis',
    'Simon',
    'Gregorio',
    'Teodoro',
    'Barrett',
    'Hank',
    'Lawrence',
    'Adolph',
    'Neville',
    'Clay',
    'Jarrett',
    'Sol',
    'Ariel',
    'Pedro',
    'Glenn',
    'Lupe',
    'Mckinley',
    'Kenton',
    'Rene',
    'Mervin'
  ];

  const lastNames = [
    'Wee',
    'Lamp',
    'Tichenor',
    'Cronin',
    'Linquist',
    'Mackenzie',
    'Sulton',
    'Karim',
    'Misner',
    'Siegle',
    'Herrick',
    'Cifaldi',
    'Copes',
    'Lehmkuhl',
    'Gridley',
    'Drain',
    'Ketelsen',
    'Fullenkamp',
    'Merrifield',
    'Pittsley',
    'Wall',
    'Dinger',
    'Gosse',
    'Guidi',
    'Calvo',
    'Correira',
    'Trim',
    'Aubert',
    'Difilippo',
    'Peery',
    'Nicodemus',
    'Zirbel',
    'Nickel',
    'Gaulin',
    'Mcmanus',
    'Groth',
    'Albus',
    'Rippeon',
    'Calender',
    'Mansour',
    'Peart',
    'Chaplin',
    'Bossert',
    'Deville',
    'Bautch',
    'Doucette',
    'Marr',
    'Tesch',
    'Cafferty',
    'Burriss',
    'Guidotti',
    'Cousar',
    'Cree',
    'Penna',
    'Hockett',
    'Moores',
    'Swart',
    'Byerly',
    'Gargano',
    'Fontenot',
    'Culwell',
    'Cornejo',
    'Hellyer',
    'Rada',
    'Giron',
    'Oakley',
    'Mariotti',
    'Estes',
    'Marker',
    'Mattocks',
    'Musick',
    'Whitely',
    'Dao',
    'Varian',
    'Koziel',
    'Johanson',
    'Mcphearson',
    'Alaniz',
    'Ganser',
    'Zell',
    'Mcnichol',
    'Kirkpatrick',
    'Mullaney',
    'Hamill',
    'Sproles',
    'Haan',
    'Girard',
    'Toups',
    'Donnell',
    'Garrity',
    'Brownson',
    'Kellum',
    'Cocklin',
    'Custard',
    'Degreenia',
    'Goldsborough',
    'Lubin',
    'Gamache',
    'Kinzer',
    'Alaimo'
  ];

  const selectedFirstName = R.nth(Math.trunc(R.multiply(Math.random(), R.length(firstNames))), firstNames);
  const selectedLastName = R.nth(Math.trunc(R.multiply(Math.random(), R.length(lastNames))), lastNames);

  return R.join(' ', [selectedFirstName, selectedLastName]);
}


function generatePlayer() {
  function generateId() {
    const id1 = Math.round(Math.random() * 1000000000);
    const id2 = Math.round(Math.random() * 1000000000);
    return Number(R.join('', [id1, id2]));
  }

  function range(min, max) {
    return Math.floor(R.add(R.multiply(Math.random(), R.subtract(max, min)), min));
  }

  function charact(min) {
    return range(100, min);
  }

  return {
    id: generateId(),
    name: generateName(),
    height: range(155, 220),
    charact: {
      ft: charact(50),
      twoPts: charact(30),
      threePts: charact(20)
    }
  };
}

exports.generatePlayer = generatePlayer;
